# Generated by Django 6.0.6 on 2026-06-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='banners/')),
                ('image2', models.ImageField(upload_to='banners/')),
                ('image3', models.ImageField(upload_to='banners/')),
            ],
        ),
    ]
