# Generated by Django 6.0.6 on 2026-06-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.TextField()),
                ('discount', models.CharField(max_length=50)),
                ('button1_text', models.CharField(max_length=50)),
                ('button1_link', models.CharField(max_length=255)),
                ('button2_text', models.CharField(max_length=50)),
                ('button2_link', models.CharField(max_length=255)),
                ('image1', models.ImageField(upload_to='banner/')),
                ('image2', models.ImageField(upload_to='banner/')),
                ('image3', models.ImageField(upload_to='banner/')),
                ('background_color', models.CharField(default='#0f172a', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
